### ISSUE TITLE
Problem running on Passenger

### ISSUE THREAD

**Issue by jaryl** [bcurren/freshbooks.rb#1]
Ruby it on a mogrel server directly is fine.

But when I run it on passenger, it says that it can't find the gem.

```
    Run `rake gems:install` to install the missing gems.
    Missing these required gems:
      bcurren-freshbooks.rb

    You're running:
      ruby 1.8.6.287 at /opt/ruby-enterprise-1.8.6-20090421/bin/ruby
```

In my environment.rb, I have done this:

```
    config.gem "bcurren-freshbooks.rb", :lib => "freshbooks", :source => "http://gems.github.com"
```

Instead of:

```
    require 'freshbooks'
```

I've checked that the gem is installed:

```
    [*@*]# gem list bcurren

    *** LOCAL GEMS ***

    bcurren-freshbooks.rb (3.0.2)
```

What could be the issue? This is on a production CentOS machine.

**Comment by nielsm** [comment]
Did you bounce the passenger instance using touch tmp/restart.txt ?  Without doing that passenger won't reload the environment to see the updated gem require.
