### ISSUE TITLE
Unable to update Recurring objects

### ISSUE THREAD

**Issue by joshcutler** [bcurren/freshbooks.rb#7]
Any attempt to update recurring objects seems to fail for me.  Is this a known issue and are there any workarounds?

Thanks,
-=Josh

**Comment by bcurren** [comment]
We don't use recurring objects so I've never tested it myself. What problems are you seeing? Please send me more details and a stack trace if possible.

**Comment by joshcutler** [comment]
Hey, I figured out the issue and it wasn't with your code.  If you get a recurring object, the frequency os of the format "m" for monthly or "y" for yearly, but if you update/create an object they require that frequency is "month" or "year" so their API is just a little wonky.
